package com.payitnz.model;

import org.springframework.web.multipart.MultipartFile;

public class ReconcillationBean {
	int id; // autogenerated primary key in table   
    int adminId; // th is the id of the admin user.
    String partnerTransactionId;
    String transactionId; 
    String transactionAmount;
    String chargeAmount;
	String currency;
    String paymentTime;
    String transactionType;
    String remark;
    String uploadedDate;
    int reconcillationStatus;
    MultipartFile reconcillationFile;
    int fileId;
    
    public int getFileId() {
		return fileId;
	}

	public void setFileId(int fileId) {
		this.fileId = fileId;
	}

	public int getMerchantId() {
		return merchantId;
	}

	public void setMerchantId(int merchantId) {
		this.merchantId = merchantId;
	}

	public String getMerchantEmail() {
		return merchantEmail;
	}

	public void setMerchantEmail(String merchantEmail) {
		this.merchantEmail = merchantEmail;
	}

	int merchantId;
    String merchantEmail;
     
    public MultipartFile getReconcileFile() {
		return reconcillationFile;
	}

	public void setReconcileFile(MultipartFile reconcileFile) {
		this.reconcillationFile = reconcileFile;
	}

	public void setChargeAmount(String chargeAmount) {
		this.chargeAmount = chargeAmount;
	}

	public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getAdminId() {
        return adminId;
    }

    public void setAdminId(int adminId) {
        this.adminId = adminId;
    }
    
    public String getPartnerTransactionId() {
        return this.partnerTransactionId;
    }

    public void setPartnerTransactionId(String partnerTransactionId) {
        this.partnerTransactionId = partnerTransactionId;
    }

    public String getTransactionId() {
        return this.transactionId;
    }

    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId;
    }

    public String getTransactionAmount() {
        return this.transactionAmount;
    }

    public void setTransactionAmount(String transactionAmount) {
        this.transactionAmount = transactionAmount;
    }

	public String getChargeAmount() {
		return this.chargeAmount;
	}

	public void setChangeAmount(String chargeAmount) {
		this.chargeAmount = chargeAmount;
	}

	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}
	
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getPaymentTime() {
		return this.paymentTime;
	}

	public void setPaymentTime(String paymentTime) {
		this.paymentTime = paymentTime;
	}

	public String getTransactionType() {
		return this.transactionType;
	}

	public void setTransactionType(String type) {
		this.transactionType = type;
	}

	public int getReconcillationStatus() {
		return this.reconcillationStatus;
	}

	public void setReconcillationStatus(int status) {
		this.reconcillationStatus = status;
	}

	public String getUploadedDate() {
		return this.uploadedDate;
	}

	public void setUploadedDate(String date) {
		this.uploadedDate = date;
	}			
}
