package com.payitnz.model;

import java.util.List;

import org.springframework.web.multipart.MultipartFile;

public class User {
    
    int id; // autogenerated primary key in table
    
    String infidigiAccountId; // Unique id in Payitnz to identify each merchant.

    String infidigiUserId;

    String infidigiPassword;
   
	String lastName;
    
    String firstName;
    
    String username;
    
    String companyName;
    
    String phoneNo;
    
    String email;
    
    String status;
    
    int roleId;
    
    String retypeEmail;
    
    int creator_id=0;
    
	int verified; 
	
	String created_date;
    
    String search_string;
    
	List<MultipartFile> files;
	
	List<String> file_name;
	
	List<String> file_description;

	String company_registration_id;
	
 	String trading_name;
 	
 	String company_registered_name;
 	
 	String retypePassword;
 	
 	String last_logged_in_at;
 	
 	int all_permission;
 	
 	int permission_refund;
 	
 	int permission_setup_merchant;
 	
 	int permission_setup_users;
 	
 	int permission_setup_connections;
 	
 	int permission_access_app;
 	
 	int permission_settlement;
 	
 	int permission_reconciliation;
 	
 	int permission_alipay_transactions;
 	
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getInfidigiAccountId() {
        return infidigiAccountId;
    }

    public void setInfidigiAccountId(String infidigiAccountId) {
        this.infidigiAccountId = infidigiAccountId;
    }

    public String getInfidigiUserId() {
        return infidigiUserId;
    }

    public void setInfidigiUserId(String infidigiUserId) {
        this.infidigiUserId = infidigiUserId;
    }

    public String getInfidigiPassword() {
        return infidigiPassword;
    }

    public void setInfidigiPassword(String infidigiPassword) {
        this.infidigiPassword = infidigiPassword;
    }
    
    public String getLastName() {
 		return lastName;
 	}

 	public void setLastName(String lastName) {
 		this.lastName = lastName;
 	}

 	public String getFirstName() {
 		return firstName;
 	}

 	public void setFirstName(String firstName) {
 		this.firstName = firstName;
 	}

 	public String getUsername() {
 		return username;
 	}

 	public void setUsername(String username) {
 		this.username = username;
 	}

 	public String getCompanyName() {
 		return companyName;
 	}

 	public void setCompanyName(String companyName) {
 		this.companyName = companyName;
 	}

 	public String getPhoneNo() {
 		return phoneNo;
 	}

 	public void setPhoneNo(String phoneNo) {
 		this.phoneNo = phoneNo;
 	}

 	public String getEmail() {
 		return email;
 	}

 	public void setEmail(String email) {
 		this.email = email;
 	}

 	public String getStatus() {
 		return status;
 	}

 	public void setStatus(String status) {
 		this.status = status;
 	}

 	public int getRoleId() {
 		return roleId;
 	}

 	public void setRoleId(int roleId) {
 		this.roleId = roleId;
 	}

 	public String getCompany_registration_id() {
		return company_registration_id;
	}

	public void setCompany_registration_id(String company_registration_id) {
		this.company_registration_id = company_registration_id;
	}

	public String getTrading_name() {
		return trading_name;
	}

	public void setTrading_name(String trading_name) {
		this.trading_name = trading_name;
	}

	public String getCompany_registered_name() {
		return company_registered_name;
	}

	public void setCompany_registered_name(String company_registered_name) {
		this.company_registered_name = company_registered_name;
	}

	public String getRetypeEmail() {
		return retypeEmail;
	}

	public void setRetypeEmail(String retypeEmail) {
		this.retypeEmail = retypeEmail;
	}

	public int getCreator_id() {
		return creator_id;
	}

	public void setCreator_id(int creator_id) {
		this.creator_id = creator_id;
	}

	public int getVerified() {
		return verified;
	}

	public void setVerified(int verified) {
		this.verified = verified;
	}

	public String getCreated_date() {
		return created_date;
	}

	public void setCreated_date(String created_date) {
		this.created_date = created_date;
	}

	public String getSearch_string() {
		return search_string;
	}

	public void setSearch_string(String search_string) {
		this.search_string = search_string;
	}

	public List<MultipartFile> getFiles() {
		return files;
	}

	public void setFiles(List<MultipartFile> files) {
		this.files = files;
	}

	public List<String> getFile_name() {
		return file_name;
	}

	public void setFile_name(List<String> file_name) {
		this.file_name = file_name;
	}

	public List<String> getFile_description() {
		return file_description;
	}

	public void setFile_description(List<String> file_description) {
		this.file_description = file_description;
	}

	public String getRetypePassword() {
		return retypePassword;
	}

	public void setRetypePassword(String retypePassword) {
		this.retypePassword = retypePassword;
	}

	public String getLast_logged_in_at() {
		return last_logged_in_at;
	}

	public void setLast_logged_in_at(String last_logged_in_at) {
		this.last_logged_in_at = last_logged_in_at;
	}

	public int getPermission_refund() {
		return permission_refund;
	}

	public void setPermission_refund(int permission_refund) {
		this.permission_refund = permission_refund;
	}
	
	public int getPermission_setup_users() {
		return permission_setup_users;
	}

	public void setPermission_setup_users(int permission_setup_users) {
		this.permission_setup_users = permission_setup_users;
	}

	public int getPermission_access_app() {
		return permission_access_app;
	}

	public void setPermission_access_app(int permission_access_app) {
		this.permission_access_app = permission_access_app;
	}

	public int getPermission_settlement() {
		return permission_settlement;
	}

	public void setPermission_settlement(int permission_settlement) {
		this.permission_settlement = permission_settlement;
	}

	public int getPermission_reconciliation() {
		return permission_reconciliation;
	}

	public void setPermission_reconciliation(int permission_reconciliation) {
		this.permission_reconciliation = permission_reconciliation;
	}

	public int getAll_permission() {
		return all_permission;
	}

	public void setAll_permission(int all_permission) {
		this.all_permission = all_permission;
	}

	public int getPermission_setup_connections() {
		return permission_setup_connections;
	}

	public void setPermission_setup_connections(int permission_setup_connections) {
		this.permission_setup_connections = permission_setup_connections;
	}

	public int getPermission_alipay_transactions() {
		return permission_alipay_transactions;
	}

	public void setPermission_alipay_transactions(int permission_alipay_transactions) {
		this.permission_alipay_transactions = permission_alipay_transactions;
	}

	public int getPermission_setup_merchant() {
		return permission_setup_merchant;
	}

	public void setPermission_setup_merchant(int permission_setup_merchant) {
		this.permission_setup_merchant = permission_setup_merchant;
	}

}
